config/routes.rb
Temp::Application.routes.draw do
  
  

  devise_for :users, :path_names => { :sign_up => "register", :sign_in => "login", :sign_out => "logout" }
  get "welcome/index"

  root to: 'welcome#index'

  resources :posts,
            :path_names => {
                  :new => "nouveauprojet" }

  resources :entrepreneurs
  resources :categories
  resources :temoins
  resources :articles
  resources :entreprises
  resources :actus
  get '/posts_termines' => 'posts#index_term'
  get '/posts_en_cours' => 'posts#index_cours'
  get '/presentation' => 'pages#pres'
  get '/equipe' => 'pages#equipe'
  get '/contacts' => 'pages#contact'
 

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
   

    if user
      can :manage, :all
  else
      can :read, :all
    end
    #.role? :admin
     # can :manage, :all
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/actu.rb
class Actu < ActiveRecord::Base

	has_many :liens
	accepts_nested_attributes_for :liens, :reject_if => lambda { |l| l[:link].blank? },
			:allow_destroy => true

	has_many :actu_images
	accepts_nested_attributes_for :actu_images,
			:allow_destroy => true	
			
	has_many :videos
	accepts_nested_attributes_for :videos, :reject_if => lambda { |v| v[:link].blank? },
			:allow_destroy => true			


			
end

app/models/actu_image.rb
class ActuImage < ActiveRecord::Base

	belongs_to :actu

	has_attached_file :image, :styles => { square: "350x350>", colonne: "250x250>" }
						


end

app/models/article.rb
class Article < ActiveRecord::Base
	has_attached_file :image, :styles => { :icone => "100x100>" }

	validates_attachment_size :image, :less_than => 5.megabytes

end

app/models/categorie.rb
class Categorie < ActiveRecord::Base
end

app/models/ent_image.rb
class EntImage < ActiveRecord::Base
	belongs_to :entrepreneur
	has_attached_file :image, :styles => { :icone => "100x100>" }
end

app/models/entrepreneur.rb
class Entrepreneur < ActiveRecord::Base
	

	
	has_many :posts
	has_many :vidents, :dependent => :destroy
	accepts_nested_attributes_for :vidents, :reject_if => lambda { |v| v[:link].blank? },
				:allow_destroy => true

	has_many :ent_images, :dependent => :destroy
	accepts_nested_attributes_for :ent_images,
				:allow_destroy => true			


	has_many :taggings
	has_many :tags, through: :taggings

	#def self.tagged_with(name)
  	#	Tag.find_by_name!(name).entrepreneurs
	#end

	#def self.tag_counts
  	#	Tag.select("tags.*, count(taggings.tag_id) as count").
    #	joins(:taggings).group("taggings.tag_id")
	#end

	#def tag_list
  	#	tags.map(&:name).join(", ")
	#end

	#def tag_list=(names)
  	#	self.tags = names.split(",").map do |n|
    #	Tag.where(name: n.strip).first_or_create!
  	#end
	#end
end

app/models/entreprise.rb
class Entreprise < ActiveRecord::Base

	has_attached_file :image, :styles => { :icone => "125x125>" }

	validates_attachment_size :image, :less_than => 5.megabytes

	
end

app/models/lien.rb
class Lien < ActiveRecord::Base

	belongs_to :actu
end

app/models/partenaire.rb
class Partenaire < ActiveRecord::Base

	belongs_to :post

	has_attached_file :image, :styles => { :icone => "100x100>" }

	#validates_attachment_presence :image
	validates_attachment_size :image, :less_than => 5.megabytes
end

app/models/post.rb
class Post < ActiveRecord::Base

	

	validates :title, presence: true

	belongs_to :entrepreneur

	belongs_to :categorie
	
	has_attached_file :image, :styles => { :frise => "1000x300" }
	
	has_many :partenaires
	accepts_nested_attributes_for :partenaires,
			:allow_destroy => true

	has_many :vidposts
	accepts_nested_attributes_for :vidposts,
			:allow_destroy => true		

	has_attached_file :calendar

	#validates_attachment_presence :image
	validates_attachment_size :image, :less_than => 10.megabytes

end

app/models/temoin.rb
class Temoin < ActiveRecord::Base

	has_attached_file :image, :styles => { :icone => "100x100>" }
	has_attached_file :imagecole, :styles => { :icone => "75x75>" }

	#validates_attachment_presence :image
	validates_attachment_size :image, :less_than => 5.megabytes

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vident.rb
class Vident < ActiveRecord::Base
	belongs_to :entrepreneur
end

app/models/video.rb
class Video < ActiveRecord::Base

	belongs_to :actu

end

app/models/vidpost.rb
class Vidpost < ActiveRecord::Base
	belongs_to :post
end

app/controllers/entrepreneurs_controller.rb
class EntrepreneursController < ApplicationController
	before_filter :authenticate_user!

	
	def new
		@entrepreneur = Entrepreneur.new
		@actu = Actu.last
	end

	def create
		@entrepreneur = Entrepreneur.new(params[:entrepreneur].permit(:nom, :description, :lien, :lien2, :nbp, :tag_list,
																vidents_attributes: [:link, :youvim, :entrepreneur_id, :id, :_destroy], 
																ent_images_attributes: [:image, :entrepreneur_id, :id, :_destroy]))
		@entrepreneur.save
		redirect_to @entrepreneur
	end

	def show
		@entrepreneur = Entrepreneur.find(params[:id])
		@actu = Actu.last
	end

	def index
		@entrepreneurs = Entrepreneur.all
		@actu = Actu.last
	end

	def edit
		@entrepreneur = Entrepreneur.find(params[:id])
		@actu = Actu.last
	end

	def update
		@entrepreneur = Entrepreneur.find(params[:id])
		@entrepreneur.update(params[:entrepreneur].permit(:nom, :description, :lien, :lien2, :nbp, :tag_list,
														vidents_attributes: [:link, :youvim, :entrepreneur_id, :id, :_destroy], 
														ent_images_attributes: [:image, :entrepreneur_id, :id, :_destroy]))
		redirect_to @entrepreneur
	end

	def destroy
		@entrepreneur = Entrepreneur.find(params[:id])
		@entrepreneur.destroy

		redirect_to entrepreneurs_path
	end

end

app/helpers/actus_helper.rb
module ActusHelper
end

app/helpers/entrepreneur_helper.rb
module EntrepreneurHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def tab(value)
		@page_tab = value
	end
end

app/helpers/temoins_helper.rb
module TemoinsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/entrepreneurs/_ent_image_fields.html.erb
    <%= f.label :image, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :image %>
    </div>
    <%= f.check_box '_destroy' %> Supprimer l'image
  

app/views/entrepreneurs/_form.html.erb
<%= form_for @entrepreneur, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :nom, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nom, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :lien, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :lien, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :note_de_bas_de_page, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nbp, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :lien_bas_de_page, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :lien2, :class => 'text_field' %>
    </div>
  </div>



  <%= f.fields_for :ent_images do |iform| %>
        <% render 'ent_image_fields', :f => iform %>
        <% end %>
        <p><%= link_to_add_fields "Add image", f, :ent_images %></p>

  <%= f.fields_for :vidents do |vform| %>
        <% render 'vident_fields', :f => vform %>
        <% end %>
        <p><%= link_to_add_fields "Add video", f, :vidents %></p>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                entrepreneurs_path, :class => 'btn' %>
  </div>
<% end %>

app/views/entrepreneurs/_vident_fields.html.erb
 <div class="control-group">
    <%= f.label :type_video, :class => 'control-label' %>
    <div class="controls">
  <%= f.select :youvim, [['Youtube', true], ['Vimeo', false]] %>
  </div>
  </div>


 <div class="control-group">
    <%= f.label :video, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :link, :class => 'text_field' %>
    </div>
    <%= f.check_box '_destroy' %>  Supprimer la video
  </div>

app/views/entrepreneurs/edit.html.erb
<%- model_class = Entrepreneur -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/entrepreneurs/index.html.erb
<%- model_class = Entrepreneur -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:nom) %></th>
      <th><%= model_class.human_attribute_name(:lien) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @entrepreneurs.each do |entrepreneur| %>
      <tr>
        <td><%= link_to entrepreneur.nom, entrepreneur_path(entrepreneur) %></td>
        <td><a <%= link_to 'Site', entrepreneur.lien %></a></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_entrepreneur_path(entrepreneur), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      entrepreneur_path(entrepreneur),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_entrepreneur_path,
            :class => 'btn btn-primary' %>

            <%= link_to t('.posts', :default => t("helpers.links.posts")),
            posts_path,
            :class => 'btn btn-primary' %>

app/views/entrepreneurs/new.html.erb
<%- model_class = Entrepreneur -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/entrepreneurs/show.html.erb
<%- model_class = Entrepreneur -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><% for ent_image in @entrepreneur.ent_images %>
      <%= image_tag ent_image.image.url %>
      <% end %></dt>
  <dd><%= @entrepreneur.nom %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @entrepreneur.description %></dd>
  <dd><%= @entrepreneur.nbp %> cliquez <%= link_to "ici", @entrepreneur.lien2 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lien) %>:</strong></dt>
  <dd><%= @entrepreneur.lien %></dd>
  <% for vident in @entrepreneur.vidents %>
        <% if vident.youvim == true %>
        <dd><iframe width="560" height="315" src="http://www.youtube.com/embed/<%= vident.link %>" frameborder="0" allowfullscreen></iframe></dd>
        <% else %>
        <dd><iframe src="http://player.vimeo.com/video/<%= vident.link %>" width="560" height="315" frameborder="0" allowFullScreen></iframe></dd>
        <% end %>
        <% end %>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              entrepreneurs_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_entrepreneur_path(@entrepreneur), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              entrepreneur_path(@entrepreneur),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>