config/routes.rb
Temp::Application.routes.draw do
  
  

  devise_for :users, :path_names => { :sign_up => "register", :sign_in => "login", :sign_out => "logout" }
  get "welcome/index"

  root to: 'welcome#index'

  resources :posts,
            :path_names => {
                  :new => "nouveauprojet" }

  resources :entrepreneurs
  resources :categories
  resources :temoins
  resources :articles
  resources :entreprises
  resources :actus
  get '/posts_termines' => 'posts#index_term'
  get '/posts_en_cours' => 'posts#index_cours'
  get '/presentation' => 'pages#pres'
  get '/equipe' => 'pages#equipe'
  get '/contacts' => 'pages#contact'
 

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
   

    if user
      can :manage, :all
  else
      can :read, :all
    end
    #.role? :admin
     # can :manage, :all
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/actu.rb
class Actu < ActiveRecord::Base

	has_many :liens
	accepts_nested_attributes_for :liens, :reject_if => lambda { |l| l[:link].blank? },
			:allow_destroy => true

	has_many :actu_images
	accepts_nested_attributes_for :actu_images,
			:allow_destroy => true	
			
	has_many :videos
	accepts_nested_attributes_for :videos, :reject_if => lambda { |v| v[:link].blank? },
			:allow_destroy => true			


			
end

app/models/actu_image.rb
class ActuImage < ActiveRecord::Base

	belongs_to :actu

	has_attached_file :image, :styles => { square: "350x350>", colonne: "250x250>" }
						


end

app/models/article.rb
class Article < ActiveRecord::Base
	has_attached_file :image, :styles => { :icone => "100x100>" }

	validates_attachment_size :image, :less_than => 5.megabytes

end

app/models/categorie.rb
class Categorie < ActiveRecord::Base
end

app/models/ent_image.rb
class EntImage < ActiveRecord::Base
	belongs_to :entrepreneur
	has_attached_file :image, :styles => { :icone => "100x100>" }
end

app/models/entrepreneur.rb
class Entrepreneur < ActiveRecord::Base
	

	
	has_many :posts
	has_many :vidents, :dependent => :destroy
	accepts_nested_attributes_for :vidents, :reject_if => lambda { |v| v[:link].blank? },
				:allow_destroy => true

	has_many :ent_images, :dependent => :destroy
	accepts_nested_attributes_for :ent_images,
				:allow_destroy => true			


	has_many :taggings
	has_many :tags, through: :taggings

	#def self.tagged_with(name)
  	#	Tag.find_by_name!(name).entrepreneurs
	#end

	#def self.tag_counts
  	#	Tag.select("tags.*, count(taggings.tag_id) as count").
    #	joins(:taggings).group("taggings.tag_id")
	#end

	#def tag_list
  	#	tags.map(&:name).join(", ")
	#end

	#def tag_list=(names)
  	#	self.tags = names.split(",").map do |n|
    #	Tag.where(name: n.strip).first_or_create!
  	#end
	#end
end

app/models/entreprise.rb
class Entreprise < ActiveRecord::Base

	has_attached_file :image, :styles => { :icone => "125x125>" }

	validates_attachment_size :image, :less_than => 5.megabytes

	
end

app/models/lien.rb
class Lien < ActiveRecord::Base

	belongs_to :actu
end

app/models/partenaire.rb
class Partenaire < ActiveRecord::Base

	belongs_to :post

	has_attached_file :image, :styles => { :icone => "100x100>" }

	#validates_attachment_presence :image
	validates_attachment_size :image, :less_than => 5.megabytes
end

app/models/post.rb
class Post < ActiveRecord::Base

	

	validates :title, presence: true

	belongs_to :entrepreneur

	belongs_to :categorie
	
	has_attached_file :image, :styles => { :frise => "1000x300" }
	
	has_many :partenaires
	accepts_nested_attributes_for :partenaires,
			:allow_destroy => true

	has_many :vidposts
	accepts_nested_attributes_for :vidposts,
			:allow_destroy => true		

	has_attached_file :calendar

	#validates_attachment_presence :image
	validates_attachment_size :image, :less_than => 10.megabytes

end

app/models/temoin.rb
class Temoin < ActiveRecord::Base

	has_attached_file :image, :styles => { :icone => "100x100>" }
	has_attached_file :imagecole, :styles => { :icone => "75x75>" }

	#validates_attachment_presence :image
	validates_attachment_size :image, :less_than => 5.megabytes

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vident.rb
class Vident < ActiveRecord::Base
	belongs_to :entrepreneur
end

app/models/video.rb
class Video < ActiveRecord::Base

	belongs_to :actu

end

app/models/vidpost.rb
class Vidpost < ActiveRecord::Base
	belongs_to :post
end

app/helpers/actus_helper.rb
module ActusHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def tab(value)
		@page_tab = value
	end
end

app/helpers/temoins_helper.rb
module TemoinsHelper
end

app/views/layouts/actus.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Le blog SenseSchool</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="robots" content="NOODP">
</head>
<body>

   <header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/posts"><%= image_tag("navss.png")%></a>
      <div class="nav-collapse">
        <ul class="nav">
          <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Programmes<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><%= link_to "Programmes ouverts", posts_path %></li>
                                <li><%= link_to "Programmes en cours", posts_en_cours_path %></li>
                                <li><%= link_to "Programmes terminés", posts_termines_path %></li>
                            </ul>
                        </li>
          <li><%= link_to "À propos", presentation_path %></li>
          <% if user_signed_in? %><li><%= link_to "Entrepreneurs", entrepreneurs_path %></li><% end %>
          <% if user_signed_in? %><li><%= link_to "Categories", categories_path %></li><% end %>
          
          <li><%= link_to "Partenaires", entreprises_path %></li>
          <li><div id="user_nav">
  <% if user_signed_in? %>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% end %>
</div></li>
        </ul>
      </div>
    </div>
  </div>
</header>





	  
    <div class="container">
      <div class="row>">
        <div class="row">
        
      <div class="span9"><%= yield %></div>
        <div class="span3"> 
          <div class="page-header">
    <h3>SenseSchool</h3>

    <p>Transformer l'éducation en permettant à chacun de résoudre les problèmes sociaux et environnementaux de notre époque.<br>
    <%= link_to 'En savoir plus', presentation_path %><br></p>
    </div>
    <div onclick="thevid=document.getElementById('thevideo'); thevid.style.display='block'; this.style.display='none'"><img src="/vidthumb.jpg" style="cursor:pointer" /></div><div id="thevideo" style="display:none">
    <iframe src="http://player.vimeo.com/video/65603869" width="250" height="141" frameborder="0" allowFullScreen></iframe>
  </div>
        </div>
        
      </div>
      </div>

  </div>

 
  <footer class="footer">
   <div class="form-actions">
      <div class="container">
        <div class="navbar navbar-static-bottom">
          <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="nav-collapse">
        <ul class="nav">
          
          <li><%= link_to "L'équipe", equipe_path %></li>
          <li><%= link_to "Le blog", actus_path %></li>
          <li><%= link_to "Presse", articles_path %></li>
          <li><%= link_to "Contacts", contacts_path %></li>
          </ul>
          <ul class="nav pull-right">
          <li><a href="https://www.facebook.com/pages/SenseSchool/424819410912643"><%= image_tag("facebook.png") %></a></li>
          <li><a href="https://twitter.com/SenseSchoolYY"><%= image_tag("twitter.png") %></a></li>
          <li><a href="http://vimeo.com/user14838507"><%= image_tag("vimeo.png") %></a></li>
          <li><%= link_to "  " %></li>
        </ul>
      </div>
    </div>
        </div>
      </div>
      </div>
    </footer>
   



</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SenseSchool</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="robots" content="NOODP">
</head>
<body>

  <header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/posts"><%= image_tag("navss.png")%></a>
      <div class="nav-collapse">
        <ul class="nav">
          <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Programmes<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><%= link_to "Programmes ouverts", posts_path %></li>
                                <li><%= link_to "Programmes en cours", posts_en_cours_path %></li>
                                <li><%= link_to "Programmes terminés", posts_termines_path %></li>
                            </ul>
                        </li>
          <li><%= link_to "À propos", presentation_path %></li>
          <% if user_signed_in? %><li><%= link_to "Entrepreneurs", entrepreneurs_path %></li><% end %>
          <% if user_signed_in? %><li><%= link_to "Categories", categories_path %></li><% end %>
          
          <li><%= link_to "Partenaires", entreprises_path %></li>
          <li><div id="user_nav">
  <% if user_signed_in? %>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% end %>
</div></li>
        </ul>
      </div>
    </div>
  </div>
</header>





	  
    <div class="container">
    	<div class="row">
       
      
        <div class="row>">
    		<div class="span9"><p class="notice"><%= notice %></p><%= yield %></div>
    		<div class="span3">
    			<div class="page-header">
        <div class="page-header">
    <h3>SenseSchool en bref</h3>

    <p>Transformer l'éducation en permettant à chacun de résoudre les problèmes sociaux et environnementaux de notre époque.<br>
    <%= link_to 'En savoir plus', presentation_path %><br></p>
    </div>
    <div onclick="thevid=document.getElementById('thevideo'); thevid.style.display='block'; this.style.display='none'"><img src="/vidthumb.jpg" style="cursor:pointer" /></div><div id="thevideo" style="display:none">
    <iframe src="http://player.vimeo.com/video/65603869" width="250" height="141" frameborder="0" allowFullScreen></iframe>
  </div>
          </div>
    	</div>
      
	</div>
</div>
</div>


  <footer class="footer">
    <div class="form-actions">
      <div class="container">
        <div class="navbar">
          <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "L'équipe", equipe_path %></li>
          <li><%= link_to "Le blog", actus_path %></li>
          <li><%= link_to "Presse", articles_path %></li>
          <li><%= link_to "Contacts", contacts_path %></li>
        </ul>
        <ul class="nav pull-right">
          <li><a href="https://www.facebook.com/pages/SenseSchool/424819410912643"><%= image_tag("facebook.png") %></a></li>
          <li><a href="https://twitter.com/SenseSchoolYY"><%= image_tag("twitter.png") %></a></li>
          <li><a href="http://vimeo.com/user14838507"><%= image_tag("vimeo.png") %></a></li>
          <li><%= link_to "  " %></li>
        </ul>
      </div>
    </div>
        </div>
      </div>
    </div>
    </footer>



</body>
</html>

app/views/layouts/post_edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SenseSchool</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="robots" content="NOODP">
</head>
<body>

   <header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/posts"><%= image_tag("navss.png")%></a>
      <div class="nav-collapse">
        <ul class="nav">
          <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Programmes<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><%= link_to "Programmes ouverts", posts_path %></li>
                                <li><%= link_to "Programmes en cours", posts_en_cours_path %></li>
                                <li><%= link_to "Programmes terminés", posts_termines_path %></li>
                            </ul>
                        </li>
          <li><%= link_to "A propos", presentation_path %></li>
          <% if user_signed_in? %><li><%= link_to "Entrepreneurs", entrepreneurs_path %></li><% end %>
          <% if user_signed_in? %><li><%= link_to "Categories", categories_path %></li><% end %>
          
          <li><%= link_to "Partenaires", entreprises_path %></li>
          <li><div id="user_nav">
  <% if user_signed_in? %>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% end %>
</div></li>
        </ul>
      </div>
    </div>
  </div>
</header>





	  
    <div class="container">
    	<div class="row">
       <p class="notice"><%= notice %></p><%= yield %>
      
        
    	</div>
	</div>

  <footer class="footer">
    <div class="form-actions">
      <div class="container">
        <div class="navbar">
          <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "L'équipe", equipe_path %></li>
          <li><%= link_to "Le blog", actus_path %></li>
          <li><%= link_to "Presse", articles_path %></li>
          <li><%= link_to "Contacts", contacts_path %></li>
        </ul>
        <ul class="nav pull-right">
          <li><a href="https://www.facebook.com/pages/SenseSchool/424819410912643"><%= image_tag("facebook.png") %></a></li>
          <li><a href="https://twitter.com/SenseSchoolYY"><%= image_tag("twitter.png") %></a></li>
          <li><a href="http://vimeo.com/user14838507"><%= image_tag("vimeo.png") %></a></li>
          <li><%= link_to "  " %></li>
        </ul>
      </div>
    </div>
        </div>
      </div>
    </div>
    </footer>
   



</body>
</html>

app/views/layouts/post_index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Programmes SenseSchool</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="robots" content="NOODP">
</head>
<body>

 <header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/posts"><%= image_tag("navss.png")%></a>
      <div class="nav-collapse">
        <ul class="nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Programmes<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Programmes ouverts", posts_path %></li>
              <li><%= link_to "Programmes en cours", posts_en_cours_path %></li>
              <li><%= link_to "Programmes terminés", posts_termines_path %></li>
            </ul>
          </li>
          <li><%= link_to "À propos", presentation_path %></li>
          <% if user_signed_in? %><li><%= link_to "Entrepreneurs", entrepreneurs_path %></li><% end %>
          <% if user_signed_in? %><li><%= link_to "Categories", categories_path %></li><% end %>
          
          <li><%= link_to "Partenaires", entreprises_path %></li>
          <li><div id="user_nav">
            <% if user_signed_in? %>
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
            <% end %>
          </div></li>
        </ul>
      </div>
    </div>
  </div>
</header>





<div class="container">
 <div class="row">
   
  
  <div class="row">
    <div class="span2"><%- model_class = Categorie -%>
      <div class="page-header">
        <h3>Catégories</h3>
      </div>
      <div class="tabbable tabs-left">
        <ul class="nav nav-pills nav-stacked">
          <li class="active"><%= link_to 'Tout', posts_path %></li>

          <% Categorie.all.each do |c| %>
          <li><a href='#tab<%= c.id %>' data-toggle="tab"><%= c.nom %> (<%= Post.where(categorie_id: c.id).count() %>)</a></li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="span7"><p class="notice"><%= notice %>

    </p><%= yield %></div>
    <div class="span3"> 
     <div class="page-header">
     <h3>Actualités</h3>
     </div>
    <h4><%= @actu.titre %></h4>
     <% for video in @actu.videos %>
     <% if video.youvim == true %>
     <iframe width="560" height="315" src="http://www.youtube.com/embed/<%= video.link %>" frameborder="0" allowfullscreen></iframe>
     <% else %>
     <dd><iframe src="http://player.vimeo.com/video/<%= video.link %>" width="560" height="315" frameborder="0" allowFullScreen></iframe></dd>
     <% end %>
     <% end %>
     <p>
      <% for actu_image in @actu.actu_images %>
      <%= image_tag actu_image.image.url(:colonne) %>
      <% end %>
    </p>
    <p><%= @actu.texte %></p>
    <% for lien in @actu.liens %>
    <%= link_to 'En savoir plus', lien.link %>
    <% end %>
    <br>
    <div class="page-header">
    <h3>SenseSchool en bref</h3>

    <p>Transformer l'éducation en permettant à chacun de résoudre les problèmes sociaux et environnementaux de notre époque.<br>
    <%= link_to 'En savoir plus', presentation_path %><br></p>
    </div>
    <div onclick="thevid=document.getElementById('thevideo'); thevid.style.display='block'; this.style.display='none'"><img src="/vidthumb.jpg" style="cursor:pointer" /></div><div id="thevideo" style="display:none">
    <iframe src="http://player.vimeo.com/video/65603869" width="250" height="141" frameborder="0" allowFullScreen></iframe>
  </div>
  </div>
</div>
</div>
</div>


<footer class="footer">
  <div class="form-actions">
  <div class="container">
    <div class="navbar">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "L'équipe", equipe_path %></li>
            <li><%= link_to "Le blog", actus_path %></li>
            <li><%= link_to "Presse", articles_path %></li>
            <li><%= link_to "Contacts", contacts_path %></li>
          </ul>
          <ul class="nav pull-right">
          <li><a href="https://www.facebook.com/pages/SenseSchool/424819410912643"><%= image_tag("facebook.png") %></a></li>
          <li><a href="https://twitter.com/SenseSchoolYY"><%= image_tag("twitter.png") %></a></li>
          <li><a href="http://vimeo.com/user14838507"><%= image_tag("vimeo.png") %></a></li>
          <li><%= link_to "  " %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
</footer>




</body>
</html>

app/views/layouts/pres.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SenseSchool</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="robots" content="NOODP">
</head>
<body>

   <header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/posts"><%= image_tag("navss.png")%></a>
      <div class="nav-collapse">
        <ul class="nav">
          <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Programmes<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><%= link_to "Programmes ouverts", posts_path %></li>
                                <li><%= link_to "Programmes en cours", posts_en_cours_path %></li>
                                <li><%= link_to "Programmes terminés", posts_termines_path %></li>
                            </ul>
                        </li>
          <li><%= link_to "À propos", presentation_path %></li>
          <% if user_signed_in? %><li><%= link_to "Entrepreneurs", entrepreneurs_path %></li><% end %>
          <% if user_signed_in? %><li><%= link_to "Categories", categories_path %></li><% end %>
          
          <li><%= link_to "Partenaires", entreprises_path %></li>
          <li><div id="user_nav">
  <% if user_signed_in? %>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% end %>
</div></li>
        </ul>
      </div>
    </div>
  </div>
</header>





	  
    <div class="container">
       <div class="row">
        <div class="span9">
       <p class="notice"><%= notice %></p><%= yield %></div>
      <div class="span3">
        
     <div class="page-header">
     <h3>Actualités</h3>
     </div>
     <h4><%= @actu.titre %></h4>
     <% for video in @actu.videos %>
     <% if video.youvim == true %>
     <iframe width="560" height="315" src="http://www.youtube.com/embed/<%= video.link %>" frameborder="0" allowfullscreen></iframe>
     <% else %>
     <dd><iframe src="http://player.vimeo.com/video/<%= video.link %>" width="560" height="315" frameborder="0" allowFullScreen></iframe></dd>
     <% end %>
     <% end %>
     <p>
      <% for actu_image in @actu.actu_images %>
      <%= image_tag actu_image.image.url(:colonne) %>
      <% end %>
    </p>
    <p><%= @actu.texte %></p>
    <% for lien in @actu.liens %>
    <%= link_to 'En savoir plus', lien.link %>
    <% end %>
    <br>
    <div class="page-header">
    <h3>SenseSchool en bref</h3>

    <p>Transformer l'éducation en permettant à chacun de résoudre les problèmes sociaux et environnementaux de notre époque.<br>
    <%= link_to 'En savoir plus', presentation_path %><br></p>
    </div>
    <div onclick="thevid=document.getElementById('thevideo'); thevid.style.display='block'; this.style.display='none'"><img src="/vidthumb.jpg" style="cursor:pointer" /></div><div id="thevideo" style="display:none">
    <iframe src="http://player.vimeo.com/video/65603869" width="250" height="141" frameborder="0" allowFullScreen></iframe>
  </div>
      </div>
        
    	</div>
	
</div>
   

  <footer class="footer">
    <div class="form-actions">
      <div class="container">
        <div class="navbar">
          <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "L'équipe", equipe_path %></li>
          <li><%= link_to "Le blog", actus_path %></li>
          <li><%= link_to "Presse", articles_path %></li>
          <li><%= link_to "Contacts", contacts_path %></li>
        </ul>
        <ul class="nav pull-right">
         <li><a href="https://www.facebook.com/pages/SenseSchool/424819410912643"><%= image_tag("facebook.png") %></a></li>
          <li><a href="https://twitter.com/SenseSchoolYY"><%= image_tag("twitter.png") %></a></li>
          <li><a href="http://vimeo.com/user14838507"><%= image_tag("vimeo.png") %></a></li>
          <li><%= link_to "  " %></li>
        </ul>
      </div>
    </div>
        </div>
      </div>
    </div>
    </footer>


</body>
</html>